// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchURL(arg1:string):Promise<string>;

export function ListTables():Promise<Array<string>>;
