// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchURL(arg1) {
  return window['go']['backend']['App']['FetchURL'](arg1);
}

export function ListTables() {
  return window['go']['backend']['App']['ListTables']();
}

export function ScanTable(arg1) {
  return window['go']['backend']['App']['ScanTable'](arg1);
}
